# Generated by Django 3.1.3 on 2021-01-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter a name', max_length=25)),
                ('last_name', models.CharField(help_text='Enter a lastname', max_length=25)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of the artwork', max_length=100)),
                ('medium', models.CharField(blank=True, choices=[('k', 'Краски'), ('a', 'Акварель'), ('s', 'Скульптура')], max_length=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myart.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('k', 'Картины'), ('p', 'Прикладное искусство'), ('s', 'Скульптура')], max_length=1)),
                ('artworks', models.ManyToManyField(to='myart.Artwork')),
            ],
        ),
    ]
