# Generated by Django 3.1.3 on 2021-01-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myart', '0002_auto_20210127_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', help_text='Enter a name', max_length=20)),
                ('status', models.FloatField(blank=True, choices=[('g', 'государственное'), ('m', 'муниципальное'), ('c', 'частное')], max_length=1)),
                ('phone', models.CharField(default='phone', help_text='Enter a phone', max_length=10)),
                ('address', models.CharField(default='address', help_text='Enter a address', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='exhibition',
            old_name='type',
            new_name='etype',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='name',
        ),
        migrations.AddField(
            model_name='artwork',
            name='creation_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.CharField(default='size', help_text='Enter a size', max_length=20),
        ),
        migrations.AddField(
            model_name='artwork',
            name='title',
            field=models.CharField(default='title', help_text='Enter a name of the artwork', max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.CharField(default='bio', help_text='Enter a bio', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birthplace',
            field=models.CharField(default='place', help_text='Enter a birthplace', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='edu',
            field=models.CharField(default='edu', help_text='Enter a edu', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(default='name', help_text='Enter a name', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(default='lastname', help_text='Enter a lastname', max_length=20),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, choices=[('k', 'Краски'), ('a', 'Акварель'), ('s', 'Скульптура')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', help_text='Enter a name', max_length=50)),
                ('area', models.FloatField(default='0', help_text='Enter a area')),
                ('phone', models.CharField(default='1234567890', help_text='Enter a phone', max_length=10)),
                ('address', models.CharField(default='address', help_text='Enter a address', max_length=50)),
                ('o', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myart.owner')),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myart.showroom'),
        ),
    ]
