# Generated by Django 3.1.3 on 2021-01-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myart', '0003_auto_20210127_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='status',
            field=models.CharField(blank=True, choices=[('g', 'государственное'), ('m', 'муниципальное'), ('c', 'частное')], max_length=1),
        ),
    ]
