# Generated by Django 3.1.3 on 2021-01-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myart', '0006_auto_20210129_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, choices=[('Краски', 'Краски'), ('a', 'Акварель'), ('s', 'Скульптура')], max_length=6, null=True),
        ),
    ]
