# Generated by Django 3.1.3 on 2021-01-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myart', '0007_auto_20210129_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, choices=[('Краски', 'Краски'), ('Акварель', 'Акварель'), ('Скульптура', 'Скульптура')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='etype',
            field=models.CharField(blank=True, choices=[('Картины', 'Картины'), ('Пр. искусство', 'Прикладное искусство'), ('Скульптура', 'Скульптура')], max_length=13),
        ),
        migrations.AlterField(
            model_name='owner',
            name='status',
            field=models.CharField(blank=True, choices=[('гос', 'государственное'), ('мун', 'муниципальное'), ('част', 'частное')], max_length=4),
        ),
    ]
